.gitignore
.identity/00_data.tf
.identity/02_application_action.tf
.identity/03_github_environment.tf
.identity/99_main.tf
.identity/99_variables.tf
.identity/env/dev/backend.ini
.identity/env/dev/backend.tfvars
.identity/env/dev/terraform.tfvars
.identity/env/prod/backend.ini
.identity/env/prod/backend.tfvars
.identity/env/prod/terraform.tfvars
.identity/env/uat/backend.ini
.identity/env/uat/backend.tfvars
.identity/env/uat/terraform.tfvars
.identity/terraform.sh

Depend on https://github.com/pagopa/pagopa-pdf-engine/pull/2
- Introduced .identity folder for Github Runner management
Addition required in order to execute the release&deploy Github workflow

[PRDP-40] ci: Added .identity terraform folder

---

openapi/openapi.json

- Fixed openapi specs, changed /pdf-engine to /generate-pdf
Fixed wrongly inserted API in openapi specs

[PRDP-13] fix: updated openapi specs

---

src/main/java/it/gov/pagopa/project/HttpTriggerGeneratePDFFunction.java
src/main/java/it/gov/pagopa/project/model/AppErrorCodeEnum.java
src/main/java/it/gov/pagopa/project/model/GeneratePDFInput.java
src/main/java/it/gov/pagopa/project/service/impl/ParseRequestBodyServiceImpl.java
src/test/java/it/gov/pagopa/project/HttpTriggerFunctionTest.java
src/test/java/it/gov/pagopa/project/HttpTriggerGeneratePDFFunctionTest.java

- Added check on template field
- Updated unit test
Added missing check on input template field
Updated unit test

[PRDP-46] feat: Added check on template field

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml

- Updated number of minimun and maximum replicas for uat (1-3)
Reducing number of replicas in UAT deployment from unnecessary default values

[PRDP-49] ci: Updated uat chart replica numbers

---

LICENSE

- Removed MIT license from License file

chore: removed MIT license

---

performance-test/nginx/nginx.conf

[fix-environment-nginx] Changed nginx proxy url environment

---

.devops/performance-test-pipelines.yml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
performance-test/src/test-types/constant.json

- Added constant scenario to performance tests
- Changed resources allocated for performance tests
[Issue PRDP-75](https://pagopa.atlassian.net/browse/PRDP-86?atlOrigin=eyJpIjoiMDA2MGM0ZTExNGQ5NGU5NDhkNTNjZmRmNDZiYzliNzMiLCJwIjoiaiJ9)

[PRDP-75] Tuning performance tests

---

docker/run_docker.sh

…ore declaring service started
- Updated run_docker script to properly check when the service started

fix: updated run_docker.sh 

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

fix deploy

---

.identity/02_application_action.tf

fix: Service Principal per accesso a KV Int test

---

Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

- Updated to use opentelemetry agent instead of elk APM

[PRDP-95] feat update to opentelemetry agent

---

performance-test/src/test-types/constant.json

Prf test tuning

---

helm/values-uat.yaml

fix: Uat deploy

---

src/main/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImpl.java

- Introducing NETWORK_IDLE waiting

[PRDP-100] feat: Manage NETWORK_IDLE waiting

---

performance-test/src/modules/pdf_engine_client.js

- configured k6 to not ignore response body
Fix performance test
Run performance tests

[PRDP-110] fix: Configure k6 to not ignore response body

---

.github/workflows/integration_test.yml
.identity/00_data.tf
.identity/02_application_action.tf
.identity/03_github_environment.tf

- added integration test action
Run integration test on all environment

[PRDP-111] feat: Add integration test action

---

.github/workflows/integration_test.yml

fix notification message

---

helm/Chart.yaml

Updated app name in Chart.yaml

[fix] Fixed app name in chart.yaml

---

.github/workflows/integration_test.yml

- Run integration test action with the selfhosted runner used by deployment
- Set default environment to UAT for integration test 
- Change schedule time to 08:00 am
Allow to run integration test action on UAT
expected)

[PRDP-123] feat: Use deployment selfhosted runner for integration test

---

helm/values-uat.yaml
src/main/java/it/gov/pagopa/pdf/engine/Info.java

fix: info and uat helm

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
pom.xml
src/main/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunction.java
src/main/java/it/gov/pagopa/pdf/engine/Info.java
src/main/java/it/gov/pagopa/pdf/engine/service/impl/ParseRequestBodyServiceImpl.java
src/test/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunctionTest.java
src/test/resources/logback-test.xml

- Added environment variable `WORKING_DIRECTORY_PATH` 
- Fixed unit test
- Added logback-test.xml for tests
Avoid function host restart
Run unit test and local execution

[PRDP-137] fix: Move working directory to avoid host restart

---

src/main/java/it/gov/pagopa/pdf/engine/Info.java

Removed request to node app in info trigger

[test] Removed request to node app in info trigger

---

helm/values-uat.yaml

new deploy

---

performance-test/src/test-types/constant.json

fix contatst

---

.devops/performance-test-pipelines.yml
performance-test/src/test-types/constant_minor.json
src/main/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunction.java
src/main/java/it/gov/pagopa/pdf/engine/service/GeneratePDFService.java
src/main/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImpl.java
src/test/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunctionTest.java
src/test/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImplTest.java

Added logs in key points in the function
Better monitoring of function timings

[feat] Add more log to pdf generation

---

.devops/performance-test-pipelines.yml
Dockerfile
performance-test/src/test-types/constant_minor.json
src/main/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunction.java
src/main/java/it/gov/pagopa/pdf/engine/service/GeneratePDFService.java
src/main/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImpl.java
src/test/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunctionTest.java
src/test/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImplTest.java

Try fix http1.1 curl docker file

[feat] Try fix http1.1 curl docker file

---

node/pdf-generate/handlers.js

Added logs with detailed millisecond from function's start & time to finish every step of the function

[feat] Added logs with milliseconds to nodejs app

---

node/pdf-generate/handlers.js

Added unique logs timestamp
Avoid logs overlap

[feat] Add logs timestamp node app

---

node/pdf-generate/handlers.js

[feat] Improved logs readability

---

helm/values-uat.yaml

feat: Uat perf

---

node/pdf-generate/handlers.js

[feat] Fixed console call

---

helm/values-dev.yaml
node/pdf-generate/handlers.js
node/pdf-generate/index.js
node/pdf-generate/utils/browserManager.js

Implemented optimization for page creation & html opening

[feat] Implemented optimization for page creation & html opening

---

helm/values-dev.yaml
node/pdf-generate/handlers.js
node/pdf-generate/index.js
node/pdf-generate/utils/browserManager.js

[revert] Revert merge

---

node/pdf-generate/handlers.js

Parsed data for template html
New template didn't render correctly passing data as string

[fix] Parsed data for template html

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

fix: Helm resources

---

.devops/deploy-pipelines.yml
.github/workflows/release-deploy.yml
.identity/00_data.tf
.identity/03_github_environment.tf
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml

- Reintroduced app service deployment

Prdp 144 chore reintroducing aps release on devops

---

.github/workflows/release-deploy.yml

fix: avoid skipping push on app service when not rebuilding docker image

---

src/main/java/it/gov/pagopa/pdf/engine/Info.java
src/main/java/it/gov/pagopa/pdf/engine/model/PdfEngineRequest.java
src/test/java/it/gov/pagopa/pdf/engine/InfoTest.java

I have removed unused import and code
Cleanup
I have rebuilded the code: changes impact only build

chore: Cleanup unused code

---

node/package-lock.json
node/pdf-generate/helpers/splitAndSpace.js
node/pdf-generate/utils/browserManager.js

[PRDP-119] feat: add custom splitAndSpace Helper

---

node/pdf-generate/helpers/eq.js
node/pdf-generate/helpers/not.js
node/pdf-generate/utils/browserManager.js

feat: adding not and eq custom helpers

---

.devops/deploy-pipelines.yml
.github/workflows/release-deploy.bck.hybrid
.github/workflows/release-deploy.yml

- Updated deploy pipelines to manage java engine on App Service

[PRDP-158] feat: Deploy Java engine on App Service

---

.devops/deploy-pipelines.yml
.github/workflows/release-deploy.yml

fix: Az pipe

---

.devops/deploy-pipelines.yml
.github/workflows/release-deploy.yml

fix: App service name pipe

---

.github/workflows/create_dashboard.yml

chore: Dash prod

---

.opex/pdf-engine-service-node/env/prod/config.yaml
.opex/pdf-engine-service-node/env/uat/config.yaml
.opex/pdf-engine-service/env/prod/config.yaml
.opex/pdf-engine-service/env/uat/config.yaml

- Updated .opex config to refer to base path and endpoint in overrides

feat: Updating overrides for .opex endpoints

---

node/pdf-generate/handlers.js

- Introducing waiting for content loading through puppeteer events and custom waiting

[PRDP-179] feat: introducing content waiting

---

node/pdf-generate/handlers.js

- Fixed missing reference in custom waiting for render function

Fix: waiting for render custom function fix

---

.github/maven_code_review/action.yml
.github/workflows/code_review.yml
Dockerfile
pom.xml

- Updated java version from 11 to 17
Updated since java 11 is deprecated in sonar analysis

[PRDP-193] feat: update java version

---

.github/workflows/integration_test.yml

- Upgraded integration test to avoid specific tag

chore: Updated integration_test.yml

---

node/pdf-generate/handlers.js
src/main/java/it/gov/pagopa/pdf/engine/service/impl/ParseRequestBodyServiceImpl.java

- Introduced utf-8 charset definition while converting input data in the java engine

[PRDP-222] fix: managing utf8 in data

---

node/pdf-generate/helpers/lowercase.js
node/pdf-generate/utils/browserManager.js

- Updated node engine with lowercase helper function

fix: add lower case helper in node pdf engine

---

node/pdf-generate/helpers/lowercase.js

fix: fixed lowercase function register

---

helm/values-prod.yaml

- Updated helm affinity config in PROD
[Issue PRDP-235](https://pagopa.atlassian.net/browse/PRDP-235?atlOrigin=eyJpIjoiNTEyNThhNzc3YWUwNDMzYzg4NWQ2OTRjNGJhMTk3OWIiLCJwIjoiaiJ9)

[PRDP-235] Updated helm affinity config

---

.devops/deploy-pipelines.yml
.github/workflows/release-deploy.yml

🚀 updated the deploy pipeline to handle new printit instance.

new pipelines

---

node/pdf-generate/helpers/notices/getOnlinePaymentMethodContent.js
node/pdf-generate/helpers/notices/getPhysicalPaymentMethodContent.js

fix: helpers

---

node/pdf-generate/helpers/notices/genDataMatrix.js

fix: genDataMatrix.js

---

.github/workflows/create_dashboard.yml
.opex/pdf-engine-service-apimv2/env/prod/backend.ini
.opex/pdf-engine-service-apimv2/env/prod/backend.tfvars
.opex/pdf-engine-service-apimv2/env/prod/config.yaml
.opex/pdf-engine-service-apimv2/env/prod/terraform.tfvars
.opex/pdf-engine-service-node-apimv2/env/prod/backend.ini
.opex/pdf-engine-service-node-apimv2/env/prod/backend.tfvars
.opex/pdf-engine-service-node-apimv2/env/prod/config.yaml
.opex/pdf-engine-service-node-apimv2/env/prod/terraform.tfvars

chore: Alert OPEX x apim V2

---

node/pdf-generate/partials/notices/paymentInstalments.hbs
node/pdf-generate/partials/notices/paymentPoste.hbs

fix: updated partials
